version: '2'
services:
    web:    
        image: nginx:latest
        container_name: nginx
        ports:
            - "80:80"
            - "443:443"
        restart: always
        volumes:
            - "./etc/nginx/default.conf:/etc/nginx/conf.d/default.conf"
            - "./etc/ssl:/etc/ssl"
            - "./web:/web"
        depends_on:
            - "php"
            - "mariadb"
        links:
            - "mariadb:mariadb"
            - "php:php"
    php:
        build: ./web
        container_name: php
        restart: always
        volumes:
            - "./etc/php/php.ini:/usr/local/etc/php/conf.d/php.ini"
            - ./web:/web
        links:
            - "mariadb:mariadb"
        depends_on:
            - "mariadb"
    myadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin
        ports:
            - "8080:8080"
        environment:
            - PMA_ARBITRARY=1
            - PMA_HOST=mariadb
        restart: always
        depends_on:
            - "mariadb"
    mariadb:
        image: mariadb:latest
        container_name: mariadb
        restart: always
        environment:
            - MYSQL_DATABASE=savsoftquiz_v4_0
            - MYSQL_ROOT_PASSWORD=dev
            - MYSQL_USER=dev
            - MYSQL_PASSWORD=dev
        volumes:
            - ./database/cp:/docker-entrypoint-initdb.d
        ports:
            - "3306:3306"










